/********************************************************************************
** Form generated from reading UI file 'mainwindowSpanish.ui'
**
** Created by: Qt User Interface Compiler version 5.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOWSPANISH_H
#define UI_MAINWINDOWSPANISH_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include <qcustomplot.h>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QPushButton *pushButton;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_2;
    QFrame *frame;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QLabel *label;
    QLabel *label_2;
    QTextEdit *textEdit;
    QTextEdit *textEdit_2;
    QListWidget *listWidget;
    QCustomPlot *customPlot;
    QListWidget *listWidget_2;
    QWidget *layoutWidget;
    QVBoxLayout *levelsLayout_2;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QWidget *tab_2;
    QFrame *frame_2;
    QCustomPlot *customPlot_2;
    QCustomPlot *customPlot_3;
    QFrame *frame_3;
    QLabel *label_8;
    QLabel *label_3;
    QLabel *label_10;
    QLabel *label_12;
    QLabel *label_4;
    QLabel *label_11;
    QLabel *label_9;
    QLabel *label_5;
    QLabel *label_7;
    QLabel *label_6;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLabel *label_96;
    QLabel *label_97;
    QLabel *radarPhon;
    QFrame *line;
    QWidget *tab_3;
    QFrame *line_2;
    QCustomPlot *customPlot_4;
    QCustomPlot *customPlot_6;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QCustomPlot *customPlot_5;
    QLabel *label_98;
    QLabel *label_99;
    QLabel *label_100;
    QLabel *label_101;
    QLabel *label_102;
    QLabel *label_103;
    QLabel *label_104;
    QLabel *label_105;
    QLabel *label_106;
    QLabel *radarArt;
    QWidget *tab_4;
    QCustomPlot *customPlot_7;
    QCustomPlot *customPlot_8;
    QCustomPlot *customPlot_9;
    QFrame *line_3;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLabel *label_84;
    QLabel *label_85;
    QLabel *label_86;
    QLabel *label_87;
    QLabel *label_88;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_107;
    QLabel *label_108;
    QLabel *label_109;
    QLabel *label_110;
    QLabel *label_111;
    QLabel *label_112;
    QLabel *label_113;
    QLabel *label_114;
    QLabel *label_115;
    QLabel *label_116;
    QLabel *label_117;
    QLabel *label_118;
    QLabel *radarPros;
    QWidget *tab_5;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *radarInt;
    QLabel *label_137;
    QLabel *label_138;
    QLabel *label_139;
    QLabel *label_146;
    QLabel *label_147;
    QLabel *label_148;
    QLabel *label_149;
    QLabel *label_150;
    QLabel *label_151;
    QLabel *label_152;
    QLabel *label_153;
    QLabel *label_154;
    QLabel *label_155;
    QLabel *label_156;
    QLabel *label_157;
    QLabel *label_158;
    QWidget *tab_6;
    QLabel *label_119;
    QLabel *label_120;
    QLabel *label_121;
    QLabel *label_123;
    QLabel *label_124;
    QLabel *label_125;
    QLabel *label_126;
    QLabel *label_128;
    QLabel *label_130;
    QLabel *label_131;
    QLabel *label_133;
    QLabel *label_134;
    QLabel *label_135;
    QLabel *label_122;
    QLabel *label_127;
    QLabel *label_129;
    QLabel *label_132;
    QLabel *label_136;
    QLabel *label_140;
    QLabel *label_141;
    QLabel *label_142;
    QLabel *evalmFDA;
    QFrame *line_4;
    QLabel *label_143;
    QLabel *label_144;
    QLabel *label_145;
    QLabel *label_68;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1291, 699);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 80, 1271, 551));
        QFont font;
        font.setPointSize(12);
        tabWidget->setFont(font);
        tabWidget->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        pushButton = new QPushButton(tab);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(80, 350, 221, 111));
        pushButton->setIconSize(QSize(100, 100));
        pushButton_3 = new QPushButton(tab);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(520, 350, 221, 111));
        pushButton_4 = new QPushButton(tab);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(740, 350, 221, 111));
        pushButton_2 = new QPushButton(tab);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(300, 350, 221, 111));
        frame = new QFrame(tab);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(110, 10, 1041, 321));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        pushButton_5 = new QPushButton(frame);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(320, 10, 81, 81));
        pushButton_6 = new QPushButton(frame);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(410, 10, 81, 81));
        pushButton_7 = new QPushButton(frame);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(700, 10, 111, 31));
        pushButton_7->setFont(font);
        label = new QLabel(frame);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(0, 15, 91, 21));
        QFont font1;
        font1.setPointSize(11);
        label->setFont(font1);
        label_2 = new QLabel(frame);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(0, 65, 81, 21));
        label_2->setFont(font1);
        textEdit = new QTextEdit(frame);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(90, 10, 104, 31));
        textEdit_2 = new QTextEdit(frame);
        textEdit_2->setObjectName(QStringLiteral("textEdit_2"));
        textEdit_2->setGeometry(QRect(90, 60, 104, 31));
        listWidget = new QListWidget(frame);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(210, 10, 101, 81));
        QFont font2;
        font2.setPointSize(10);
        listWidget->setFont(font2);
        customPlot = new QCustomPlot(frame);
        customPlot->setObjectName(QStringLiteral("customPlot"));
        customPlot->setGeometry(QRect(0, 100, 1021, 221));
        customPlot->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        listWidget_2 = new QListWidget(frame);
        listWidget_2->setObjectName(QStringLiteral("listWidget_2"));
        listWidget_2->setGeometry(QRect(820, 10, 201, 81));
        layoutWidget = new QWidget(frame);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(501, 9, 191, 81));
        levelsLayout_2 = new QVBoxLayout(layoutWidget);
        levelsLayout_2->setSpacing(6);
        levelsLayout_2->setContentsMargins(11, 11, 11, 11);
        levelsLayout_2->setObjectName(QStringLiteral("levelsLayout_2"));
        levelsLayout_2->setContentsMargins(0, 0, 0, 0);
        pushButton_8 = new QPushButton(tab);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(540, 470, 181, 41));
        QFont font3;
        font3.setPointSize(16);
        font3.setBold(false);
        font3.setWeight(50);
        pushButton_8->setFont(font3);
        pushButton_9 = new QPushButton(tab);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(960, 350, 221, 111));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        frame_2 = new QFrame(tab_2);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(20, 10, 731, 431));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        customPlot_2 = new QCustomPlot(frame_2);
        customPlot_2->setObjectName(QStringLiteral("customPlot_2"));
        customPlot_2->setGeometry(QRect(20, 20, 691, 191));
        customPlot_2->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        customPlot_3 = new QCustomPlot(frame_2);
        customPlot_3->setObjectName(QStringLiteral("customPlot_3"));
        customPlot_3->setGeometry(QRect(20, 230, 691, 191));
        customPlot_3->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        frame_3 = new QFrame(tab_2);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(770, 10, 431, 511));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        label_8 = new QLabel(frame_3);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(190, 0, 71, 31));
        label_8->setFont(font1);
        label_8->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_3 = new QLabel(frame_3);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(100, 0, 81, 31));
        label_3->setFont(font1);
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_10 = new QLabel(frame_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(190, 80, 71, 31));
        label_10->setFont(font1);
        label_10->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_12 = new QLabel(frame_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(190, 160, 71, 31));
        label_12->setFont(font1);
        label_12->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_4 = new QLabel(frame_3);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(90, 40, 91, 31));
        label_4->setFont(font1);
        label_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_11 = new QLabel(frame_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(190, 120, 71, 31));
        label_11->setFont(font1);
        label_11->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_9 = new QLabel(frame_3);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(190, 40, 71, 31));
        label_9->setFont(font1);
        label_9->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_5 = new QLabel(frame_3);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(100, 80, 81, 31));
        label_5->setFont(font1);
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_7 = new QLabel(frame_3);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(100, 160, 81, 31));
        label_7->setFont(font1);
        label_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_6 = new QLabel(frame_3);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(110, 120, 71, 31));
        label_6->setFont(font1);
        label_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_93 = new QLabel(frame_3);
        label_93->setObjectName(QStringLiteral("label_93"));
        label_93->setGeometry(QRect(260, 0, 81, 31));
        label_93->setFont(font1);
        label_93->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_94 = new QLabel(frame_3);
        label_94->setObjectName(QStringLiteral("label_94"));
        label_94->setGeometry(QRect(260, 40, 81, 31));
        label_94->setFont(font1);
        label_94->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_95 = new QLabel(frame_3);
        label_95->setObjectName(QStringLiteral("label_95"));
        label_95->setGeometry(QRect(260, 80, 81, 31));
        label_95->setFont(font1);
        label_95->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_96 = new QLabel(frame_3);
        label_96->setObjectName(QStringLiteral("label_96"));
        label_96->setGeometry(QRect(260, 120, 81, 31));
        label_96->setFont(font1);
        label_96->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_97 = new QLabel(frame_3);
        label_97->setObjectName(QStringLiteral("label_97"));
        label_97->setGeometry(QRect(260, 160, 91, 31));
        label_97->setFont(font1);
        label_97->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        radarPhon = new QLabel(frame_3);
        radarPhon->setObjectName(QStringLiteral("radarPhon"));
        radarPhon->setGeometry(QRect(69, 198, 311, 301));
        line = new QFrame(tab_2);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(750, 10, 20, 491));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        tabWidget->addTab(tab_2, QString());
        frame_3->raise();
        frame_2->raise();
        line->raise();
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        line_2 = new QFrame(tab_3);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(630, 10, 20, 501));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        customPlot_4 = new QCustomPlot(tab_3);
        customPlot_4->setObjectName(QStringLiteral("customPlot_4"));
        customPlot_4->setGeometry(QRect(10, 10, 421, 211));
        customPlot_4->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        customPlot_6 = new QCustomPlot(tab_3);
        customPlot_6->setObjectName(QStringLiteral("customPlot_6"));
        customPlot_6->setGeometry(QRect(760, 0, 401, 201));
        customPlot_6->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        label_15 = new QLabel(tab_3);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(430, 50, 41, 31));
        label_15->setFont(font1);
        label_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_16 = new QLabel(tab_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(480, 130, 71, 31));
        label_16->setFont(font1);
        label_16->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_17 = new QLabel(tab_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(480, 50, 71, 31));
        label_17->setFont(font1);
        label_17->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_18 = new QLabel(tab_3);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(480, 170, 71, 31));
        label_18->setFont(font1);
        label_18->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_19 = new QLabel(tab_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(430, 210, 41, 31));
        label_19->setFont(font1);
        label_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_20 = new QLabel(tab_3);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(480, 210, 71, 31));
        label_20->setFont(font1);
        label_20->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(10, 10, 10);"));
        label_21 = new QLabel(tab_3);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(430, 10, 41, 31));
        label_21->setFont(font1);
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_22 = new QLabel(tab_3);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(430, 170, 41, 31));
        label_22->setFont(font1);
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_23 = new QLabel(tab_3);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(480, 10, 71, 31));
        label_23->setFont(font1);
        label_23->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_24 = new QLabel(tab_3);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(430, 130, 41, 31));
        label_24->setFont(font1);
        label_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_25 = new QLabel(tab_3);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(480, 90, 71, 31));
        label_25->setFont(font1);
        label_25->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_26 = new QLabel(tab_3);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(430, 90, 41, 31));
        label_26->setFont(font1);
        label_26->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_27 = new QLabel(tab_3);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(430, 250, 41, 31));
        label_27->setFont(font1);
        label_27->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_28 = new QLabel(tab_3);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(480, 250, 71, 31));
        label_28->setFont(font1);
        label_28->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(10, 10, 10);"));
        label_29 = new QLabel(tab_3);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(480, 290, 71, 31));
        label_29->setFont(font1);
        label_29->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(10, 10, 10);"));
        label_30 = new QLabel(tab_3);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(430, 290, 41, 31));
        label_30->setFont(font1);
        label_30->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_31 = new QLabel(tab_3);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(480, 330, 71, 31));
        label_31->setFont(font1);
        label_31->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(10, 10, 10);"));
        label_32 = new QLabel(tab_3);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(430, 330, 41, 31));
        label_32->setFont(font1);
        label_32->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        customPlot_5 = new QCustomPlot(tab_3);
        customPlot_5->setObjectName(QStringLiteral("customPlot_5"));
        customPlot_5->setGeometry(QRect(10, 250, 421, 211));
        customPlot_5->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        label_98 = new QLabel(tab_3);
        label_98->setObjectName(QStringLiteral("label_98"));
        label_98->setGeometry(QRect(550, 10, 71, 31));
        label_98->setFont(font1);
        label_98->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_99 = new QLabel(tab_3);
        label_99->setObjectName(QStringLiteral("label_99"));
        label_99->setGeometry(QRect(550, 50, 81, 31));
        label_99->setFont(font1);
        label_99->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_100 = new QLabel(tab_3);
        label_100->setObjectName(QStringLiteral("label_100"));
        label_100->setGeometry(QRect(550, 90, 71, 31));
        label_100->setFont(font1);
        label_100->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_101 = new QLabel(tab_3);
        label_101->setObjectName(QStringLiteral("label_101"));
        label_101->setGeometry(QRect(550, 130, 81, 31));
        label_101->setFont(font1);
        label_101->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_102 = new QLabel(tab_3);
        label_102->setObjectName(QStringLiteral("label_102"));
        label_102->setGeometry(QRect(550, 170, 71, 31));
        label_102->setFont(font1);
        label_102->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_103 = new QLabel(tab_3);
        label_103->setObjectName(QStringLiteral("label_103"));
        label_103->setGeometry(QRect(560, 210, 71, 31));
        label_103->setFont(font1);
        label_103->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_104 = new QLabel(tab_3);
        label_104->setObjectName(QStringLiteral("label_104"));
        label_104->setGeometry(QRect(560, 250, 71, 31));
        label_104->setFont(font1);
        label_104->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_105 = new QLabel(tab_3);
        label_105->setObjectName(QStringLiteral("label_105"));
        label_105->setGeometry(QRect(550, 290, 71, 31));
        label_105->setFont(font1);
        label_105->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_106 = new QLabel(tab_3);
        label_106->setObjectName(QStringLiteral("label_106"));
        label_106->setGeometry(QRect(550, 330, 81, 31));
        label_106->setFont(font1);
        label_106->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        radarArt = new QLabel(tab_3);
        radarArt->setObjectName(QStringLiteral("radarArt"));
        radarArt->setGeometry(QRect(800, 200, 321, 321));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        customPlot_7 = new QCustomPlot(tab_4);
        customPlot_7->setObjectName(QStringLiteral("customPlot_7"));
        customPlot_7->setGeometry(QRect(10, 10, 591, 151));
        customPlot_7->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        customPlot_8 = new QCustomPlot(tab_4);
        customPlot_8->setObjectName(QStringLiteral("customPlot_8"));
        customPlot_8->setGeometry(QRect(10, 170, 591, 161));
        customPlot_8->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        customPlot_9 = new QCustomPlot(tab_4);
        customPlot_9->setObjectName(QStringLiteral("customPlot_9"));
        customPlot_9->setGeometry(QRect(10, 350, 581, 151));
        customPlot_9->setStyleSheet(QStringLiteral("background-color: rgb(230, 230, 230);"));
        line_3 = new QFrame(tab_4);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(600, 10, 20, 491));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_69 = new QLabel(tab_4);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(780, 20, 51, 31));
        label_69->setFont(font1);
        label_69->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_70 = new QLabel(tab_4);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(780, 60, 51, 31));
        label_70->setFont(font1);
        label_70->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_71 = new QLabel(tab_4);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(780, 100, 51, 31));
        label_71->setFont(font1);
        label_71->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_72 = new QLabel(tab_4);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(780, 140, 51, 31));
        label_72->setFont(font1);
        label_72->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_73 = new QLabel(tab_4);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(780, 180, 51, 31));
        label_73->setFont(font1);
        label_73->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_74 = new QLabel(tab_4);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(780, 220, 51, 31));
        label_74->setFont(font1);
        label_74->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_75 = new QLabel(tab_4);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(780, 260, 51, 31));
        label_75->setFont(font1);
        label_75->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_76 = new QLabel(tab_4);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(780, 300, 51, 31));
        label_76->setFont(font1);
        label_76->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_77 = new QLabel(tab_4);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(780, 340, 51, 31));
        label_77->setFont(font1);
        label_77->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_78 = new QLabel(tab_4);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(780, 380, 51, 31));
        label_78->setFont(font1);
        label_78->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_79 = new QLabel(tab_4);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(780, 420, 51, 31));
        label_79->setFont(font1);
        label_79->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_80 = new QLabel(tab_4);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(780, 460, 51, 31));
        label_80->setFont(font1);
        label_80->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_81 = new QLabel(tab_4);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(640, 20, 131, 31));
        label_81->setFont(font1);
        label_81->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_82 = new QLabel(tab_4);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(620, 60, 151, 31));
        label_82->setFont(font1);
        label_82->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_83 = new QLabel(tab_4);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(620, 100, 151, 31));
        label_83->setFont(font1);
        label_83->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_84 = new QLabel(tab_4);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(640, 140, 131, 31));
        label_84->setFont(font1);
        label_84->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_85 = new QLabel(tab_4);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(620, 180, 151, 31));
        label_85->setFont(font1);
        label_85->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_86 = new QLabel(tab_4);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(620, 220, 151, 31));
        label_86->setFont(font1);
        label_86->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_87 = new QLabel(tab_4);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(620, 260, 151, 31));
        label_87->setFont(font1);
        label_87->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_88 = new QLabel(tab_4);
        label_88->setObjectName(QStringLiteral("label_88"));
        label_88->setGeometry(QRect(620, 300, 151, 31));
        label_88->setFont(font1);
        label_88->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_89 = new QLabel(tab_4);
        label_89->setObjectName(QStringLiteral("label_89"));
        label_89->setGeometry(QRect(620, 340, 151, 31));
        label_89->setFont(font1);
        label_89->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_90 = new QLabel(tab_4);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(620, 380, 151, 31));
        label_90->setFont(font1);
        label_90->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_91 = new QLabel(tab_4);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(620, 420, 151, 31));
        label_91->setFont(font1);
        label_91->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_92 = new QLabel(tab_4);
        label_92->setObjectName(QStringLiteral("label_92"));
        label_92->setGeometry(QRect(620, 460, 151, 31));
        label_92->setFont(font1);
        label_92->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_107 = new QLabel(tab_4);
        label_107->setObjectName(QStringLiteral("label_107"));
        label_107->setGeometry(QRect(840, 260, 71, 31));
        label_107->setFont(font1);
        label_107->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_108 = new QLabel(tab_4);
        label_108->setObjectName(QStringLiteral("label_108"));
        label_108->setGeometry(QRect(840, 300, 71, 31));
        label_108->setFont(font1);
        label_108->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_109 = new QLabel(tab_4);
        label_109->setObjectName(QStringLiteral("label_109"));
        label_109->setGeometry(QRect(840, 340, 71, 31));
        label_109->setFont(font1);
        label_109->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_110 = new QLabel(tab_4);
        label_110->setObjectName(QStringLiteral("label_110"));
        label_110->setGeometry(QRect(840, 380, 71, 31));
        label_110->setFont(font1);
        label_110->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_111 = new QLabel(tab_4);
        label_111->setObjectName(QStringLiteral("label_111"));
        label_111->setGeometry(QRect(840, 420, 71, 31));
        label_111->setFont(font1);
        label_111->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_112 = new QLabel(tab_4);
        label_112->setObjectName(QStringLiteral("label_112"));
        label_112->setGeometry(QRect(830, 460, 81, 31));
        label_112->setFont(font1);
        label_112->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_113 = new QLabel(tab_4);
        label_113->setObjectName(QStringLiteral("label_113"));
        label_113->setGeometry(QRect(840, 20, 71, 31));
        label_113->setFont(font1);
        label_113->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_114 = new QLabel(tab_4);
        label_114->setObjectName(QStringLiteral("label_114"));
        label_114->setGeometry(QRect(840, 60, 71, 31));
        label_114->setFont(font1);
        label_114->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_115 = new QLabel(tab_4);
        label_115->setObjectName(QStringLiteral("label_115"));
        label_115->setGeometry(QRect(840, 100, 71, 31));
        label_115->setFont(font1);
        label_115->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_116 = new QLabel(tab_4);
        label_116->setObjectName(QStringLiteral("label_116"));
        label_116->setGeometry(QRect(840, 140, 71, 31));
        label_116->setFont(font1);
        label_116->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_117 = new QLabel(tab_4);
        label_117->setObjectName(QStringLiteral("label_117"));
        label_117->setGeometry(QRect(840, 180, 71, 31));
        label_117->setFont(font1);
        label_117->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_118 = new QLabel(tab_4);
        label_118->setObjectName(QStringLiteral("label_118"));
        label_118->setGeometry(QRect(840, 220, 71, 31));
        label_118->setFont(font1);
        label_118->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        radarPros = new QLabel(tab_4);
        radarPros->setObjectName(QStringLiteral("radarPros"));
        radarPros->setGeometry(QRect(920, 80, 331, 321));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        label_33 = new QLabel(tab_5);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 30, 391, 31));
        label_33->setFont(font1);
        label_33->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_34 = new QLabel(tab_5);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(430, 30, 361, 31));
        label_34->setFont(font1);
        label_34->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_35 = new QLabel(tab_5);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 0, 111, 21));
        label_35->setFont(font1);
        label_36 = new QLabel(tab_5);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(430, 0, 171, 21));
        label_36->setFont(font1);
        label_37 = new QLabel(tab_5);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(820, 0, 31, 21));
        label_37->setFont(font1);
        label_38 = new QLabel(tab_5);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(810, 30, 51, 31));
        label_38->setFont(font1);
        label_38->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_39 = new QLabel(tab_5);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(890, 0, 41, 21));
        label_39->setFont(font1);
        label_40 = new QLabel(tab_5);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(880, 30, 51, 31));
        label_40->setFont(font1);
        label_40->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_41 = new QLabel(tab_5);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(810, 70, 51, 31));
        label_41->setFont(font1);
        label_41->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_42 = new QLabel(tab_5);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(880, 70, 51, 31));
        label_42->setFont(font1);
        label_42->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_43 = new QLabel(tab_5);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(10, 70, 391, 31));
        label_43->setFont(font1);
        label_43->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_44 = new QLabel(tab_5);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(430, 70, 361, 31));
        label_44->setFont(font1);
        label_44->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_45 = new QLabel(tab_5);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(810, 110, 51, 31));
        label_45->setFont(font1);
        label_45->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_46 = new QLabel(tab_5);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(880, 110, 51, 31));
        label_46->setFont(font1);
        label_46->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_47 = new QLabel(tab_5);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(430, 110, 361, 31));
        label_47->setFont(font1);
        label_47->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_48 = new QLabel(tab_5);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(10, 110, 391, 31));
        label_48->setFont(font1);
        label_48->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_49 = new QLabel(tab_5);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(10, 150, 391, 31));
        label_49->setFont(font1);
        label_49->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_50 = new QLabel(tab_5);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(810, 150, 51, 31));
        label_50->setFont(font1);
        label_50->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_51 = new QLabel(tab_5);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(430, 150, 361, 31));
        label_51->setFont(font1);
        label_51->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_52 = new QLabel(tab_5);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(880, 150, 51, 31));
        label_52->setFont(font1);
        label_52->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_53 = new QLabel(tab_5);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(430, 190, 361, 31));
        label_53->setFont(font1);
        label_53->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_54 = new QLabel(tab_5);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(810, 190, 51, 31));
        label_54->setFont(font1);
        label_54->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_55 = new QLabel(tab_5);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(10, 190, 391, 31));
        label_55->setFont(font1);
        label_55->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_56 = new QLabel(tab_5);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(880, 190, 51, 31));
        label_56->setFont(font1);
        label_56->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_57 = new QLabel(tab_5);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(430, 230, 361, 31));
        label_57->setFont(font1);
        label_57->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_58 = new QLabel(tab_5);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(10, 230, 391, 31));
        label_58->setFont(font1);
        label_58->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_59 = new QLabel(tab_5);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(810, 230, 51, 31));
        label_59->setFont(font1);
        label_59->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_60 = new QLabel(tab_5);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(880, 230, 51, 31));
        label_60->setFont(font1);
        label_60->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_61 = new QLabel(tab_5);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(430, 440, 361, 71));
        label_61->setFont(font1);
        label_61->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_62 = new QLabel(tab_5);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(10, 440, 391, 71));
        label_62->setFont(font1);
        label_62->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_63 = new QLabel(tab_5);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(810, 440, 51, 31));
        label_63->setFont(font1);
        label_63->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_64 = new QLabel(tab_5);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(880, 440, 51, 31));
        label_64->setFont(font1);
        label_64->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_65 = new QLabel(tab_5);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(900, 570, 51, 41));
        label_65->setFont(font1);
        label_65->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_66 = new QLabel(tab_5);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(980, 570, 51, 41));
        label_66->setFont(font1);
        label_66->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_67 = new QLabel(tab_5);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(930, 540, 71, 21));
        label_67->setFont(font1);
        radarInt = new QLabel(tab_5);
        radarInt->setObjectName(QStringLiteral("radarInt"));
        radarInt->setGeometry(QRect(940, 40, 311, 311));
        label_137 = new QLabel(tab_5);
        label_137->setObjectName(QStringLiteral("label_137"));
        label_137->setGeometry(QRect(10, 270, 391, 41));
        label_137->setFont(font1);
        label_137->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_138 = new QLabel(tab_5);
        label_138->setObjectName(QStringLiteral("label_138"));
        label_138->setGeometry(QRect(810, 270, 51, 41));
        label_138->setFont(font1);
        label_138->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_139 = new QLabel(tab_5);
        label_139->setObjectName(QStringLiteral("label_139"));
        label_139->setGeometry(QRect(880, 270, 51, 41));
        label_139->setFont(font1);
        label_139->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_146 = new QLabel(tab_5);
        label_146->setObjectName(QStringLiteral("label_146"));
        label_146->setGeometry(QRect(430, 270, 361, 41));
        label_146->setFont(font1);
        label_146->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_147 = new QLabel(tab_5);
        label_147->setObjectName(QStringLiteral("label_147"));
        label_147->setGeometry(QRect(810, 320, 51, 31));
        label_147->setFont(font1);
        label_147->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_148 = new QLabel(tab_5);
        label_148->setObjectName(QStringLiteral("label_148"));
        label_148->setGeometry(QRect(10, 320, 391, 31));
        label_148->setFont(font1);
        label_148->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_149 = new QLabel(tab_5);
        label_149->setObjectName(QStringLiteral("label_149"));
        label_149->setGeometry(QRect(880, 320, 51, 31));
        label_149->setFont(font1);
        label_149->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_150 = new QLabel(tab_5);
        label_150->setObjectName(QStringLiteral("label_150"));
        label_150->setGeometry(QRect(430, 320, 361, 31));
        label_150->setFont(font1);
        label_150->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_151 = new QLabel(tab_5);
        label_151->setObjectName(QStringLiteral("label_151"));
        label_151->setGeometry(QRect(430, 360, 361, 31));
        label_151->setFont(font1);
        label_151->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_152 = new QLabel(tab_5);
        label_152->setObjectName(QStringLiteral("label_152"));
        label_152->setGeometry(QRect(810, 360, 51, 31));
        label_152->setFont(font1);
        label_152->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_153 = new QLabel(tab_5);
        label_153->setObjectName(QStringLiteral("label_153"));
        label_153->setGeometry(QRect(880, 360, 51, 31));
        label_153->setFont(font1);
        label_153->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_154 = new QLabel(tab_5);
        label_154->setObjectName(QStringLiteral("label_154"));
        label_154->setGeometry(QRect(10, 360, 391, 31));
        label_154->setFont(font1);
        label_154->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_155 = new QLabel(tab_5);
        label_155->setObjectName(QStringLiteral("label_155"));
        label_155->setGeometry(QRect(810, 400, 51, 31));
        label_155->setFont(font1);
        label_155->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_156 = new QLabel(tab_5);
        label_156->setObjectName(QStringLiteral("label_156"));
        label_156->setGeometry(QRect(10, 400, 391, 31));
        label_156->setFont(font1);
        label_156->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_157 = new QLabel(tab_5);
        label_157->setObjectName(QStringLiteral("label_157"));
        label_157->setGeometry(QRect(430, 400, 361, 31));
        label_157->setFont(font1);
        label_157->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_158 = new QLabel(tab_5);
        label_158->setObjectName(QStringLiteral("label_158"));
        label_158->setGeometry(QRect(880, 400, 51, 31));
        label_158->setFont(font1);
        label_158->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        tabWidget->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        label_119 = new QLabel(tab_6);
        label_119->setObjectName(QStringLiteral("label_119"));
        label_119->setGeometry(QRect(160, 30, 51, 31));
        label_119->setFont(font1);
        label_119->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_120 = new QLabel(tab_6);
        label_120->setObjectName(QStringLiteral("label_120"));
        label_120->setGeometry(QRect(210, 30, 51, 31));
        label_120->setFont(font1);
        label_120->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_121 = new QLabel(tab_6);
        label_121->setObjectName(QStringLiteral("label_121"));
        label_121->setGeometry(QRect(10, 30, 141, 31));
        label_121->setFont(font1);
        label_121->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_123 = new QLabel(tab_6);
        label_123->setObjectName(QStringLiteral("label_123"));
        label_123->setGeometry(QRect(160, 80, 51, 31));
        label_123->setFont(font1);
        label_123->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_124 = new QLabel(tab_6);
        label_124->setObjectName(QStringLiteral("label_124"));
        label_124->setGeometry(QRect(20, 80, 131, 31));
        label_124->setFont(font1);
        label_124->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_125 = new QLabel(tab_6);
        label_125->setObjectName(QStringLiteral("label_125"));
        label_125->setGeometry(QRect(160, 130, 51, 31));
        label_125->setFont(font1);
        label_125->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_126 = new QLabel(tab_6);
        label_126->setObjectName(QStringLiteral("label_126"));
        label_126->setGeometry(QRect(10, 130, 141, 31));
        label_126->setFont(font1);
        label_126->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_128 = new QLabel(tab_6);
        label_128->setObjectName(QStringLiteral("label_128"));
        label_128->setGeometry(QRect(10, 180, 141, 31));
        label_128->setFont(font1);
        label_128->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_130 = new QLabel(tab_6);
        label_130->setObjectName(QStringLiteral("label_130"));
        label_130->setGeometry(QRect(160, 180, 51, 31));
        label_130->setFont(font1);
        label_130->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_131 = new QLabel(tab_6);
        label_131->setObjectName(QStringLiteral("label_131"));
        label_131->setGeometry(QRect(20, 230, 131, 31));
        label_131->setFont(font1);
        label_131->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_133 = new QLabel(tab_6);
        label_133->setObjectName(QStringLiteral("label_133"));
        label_133->setGeometry(QRect(160, 230, 51, 31));
        label_133->setFont(font1);
        label_133->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_134 = new QLabel(tab_6);
        label_134->setObjectName(QStringLiteral("label_134"));
        label_134->setGeometry(QRect(20, 280, 131, 31));
        label_134->setFont(font1);
        label_134->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_135 = new QLabel(tab_6);
        label_135->setObjectName(QStringLiteral("label_135"));
        label_135->setGeometry(QRect(160, 280, 51, 31));
        label_135->setFont(font1);
        label_135->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_122 = new QLabel(tab_6);
        label_122->setObjectName(QStringLiteral("label_122"));
        label_122->setGeometry(QRect(210, 80, 51, 31));
        label_122->setFont(font1);
        label_122->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_127 = new QLabel(tab_6);
        label_127->setObjectName(QStringLiteral("label_127"));
        label_127->setGeometry(QRect(210, 130, 51, 31));
        label_127->setFont(font1);
        label_127->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_129 = new QLabel(tab_6);
        label_129->setObjectName(QStringLiteral("label_129"));
        label_129->setGeometry(QRect(210, 180, 51, 31));
        label_129->setFont(font1);
        label_129->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_132 = new QLabel(tab_6);
        label_132->setObjectName(QStringLiteral("label_132"));
        label_132->setGeometry(QRect(210, 230, 51, 31));
        label_132->setFont(font1);
        label_132->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_136 = new QLabel(tab_6);
        label_136->setObjectName(QStringLiteral("label_136"));
        label_136->setGeometry(QRect(210, 280, 51, 31));
        label_136->setFont(font1);
        label_136->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_140 = new QLabel(tab_6);
        label_140->setObjectName(QStringLiteral("label_140"));
        label_140->setGeometry(QRect(160, 330, 51, 31));
        label_140->setFont(font1);
        label_140->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        label_141 = new QLabel(tab_6);
        label_141->setObjectName(QStringLiteral("label_141"));
        label_141->setGeometry(QRect(220, 330, 51, 31));
        label_141->setFont(font1);
        label_141->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_142 = new QLabel(tab_6);
        label_142->setObjectName(QStringLiteral("label_142"));
        label_142->setGeometry(QRect(10, 330, 141, 31));
        label_142->setFont(font1);
        label_142->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        evalmFDA = new QLabel(tab_6);
        evalmFDA->setObjectName(QStringLiteral("evalmFDA"));
        evalmFDA->setGeometry(QRect(390, 50, 841, 411));
        line_4 = new QFrame(tab_6);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(310, 10, 20, 501));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_143 = new QLabel(tab_6);
        label_143->setObjectName(QStringLiteral("label_143"));
        label_143->setGeometry(QRect(220, 380, 51, 31));
        label_143->setFont(font1);
        label_143->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_144 = new QLabel(tab_6);
        label_144->setObjectName(QStringLiteral("label_144"));
        label_144->setGeometry(QRect(0, 380, 151, 31));
        label_144->setFont(font1);
        label_144->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_145 = new QLabel(tab_6);
        label_145->setObjectName(QStringLiteral("label_145"));
        label_145->setGeometry(QRect(160, 380, 51, 31));
        label_145->setFont(font1);
        label_145->setStyleSheet(QLatin1String("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);"));
        tabWidget->addTab(tab_6, QString());
        label_68 = new QLabel(centralWidget);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(250, 0, 831, 81));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1291, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        pushButton->setText(QString());
        pushButton_3->setText(QString());
        pushButton_4->setText(QString());
        pushButton_2->setText(QString());
        pushButton_5->setText(QString());
        pushButton_6->setText(QString());
        pushButton_7->setText(QApplication::translate("MainWindow", "Reproducir Ejemplo", nullptr));
        label->setText(QApplication::translate("MainWindow", "Nombre", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Apellido", nullptr));
        pushButton_8->setText(QApplication::translate("MainWindow", "Crear reporte", nullptr));
        pushButton_9->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Neuro Speech", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Jitter (%)", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Shimmer (%)", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "APQ (%)", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Energia (dB)", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "PPQ (%)", nullptr));
        label_93->setText(QApplication::translate("MainWindow", "0.00->1.20", nullptr));
        label_94->setText(QApplication::translate("MainWindow", "2.80->6.30", nullptr));
        label_95->setText(QApplication::translate("MainWindow", "3.10->7.70", nullptr));
        label_96->setText(QApplication::translate("MainWindow", "0.00->0.43", nullptr));
        label_97->setText(QApplication::translate("MainWindow", "12.70->17.20", nullptr));
        radarPhon->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Fonaci\303\263n", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "F2/a/", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "F2/u/", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "F1/a/", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "F1/u/", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "F2/i/", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "F1/i/", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "VSA", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "VPA", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "FCR", nullptr));
        label_98->setText(QApplication::translate("MainWindow", "643->908", nullptr));
        label_99->setText(QApplication::translate("MainWindow", "1160->1510", nullptr));
        label_100->setText(QApplication::translate("MainWindow", "275->470", nullptr));
        label_101->setText(QApplication::translate("MainWindow", "2100->2550", nullptr));
        label_102->setText(QApplication::translate("MainWindow", "350->490", nullptr));
        label_103->setText(QApplication::translate("MainWindow", "600->1600", nullptr));
        label_104->setText(QApplication::translate("MainWindow", "534->1073", nullptr));
        label_105->setText(QApplication::translate("MainWindow", "127->407", nullptr));
        label_106->setText(QApplication::translate("MainWindow", "0.84->1.27", nullptr));
        radarArt->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Articulaci\303\263n", nullptr));
        label_69->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_70->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_71->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_72->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_73->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_74->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_75->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_76->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_77->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_78->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_79->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_80->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_81->setText(QApplication::translate("MainWindow", "Rata Sonoros [1/s]", nullptr));
        label_82->setText(QApplication::translate("MainWindow", "Dur. Prom. Sonoro [ms]", nullptr));
        label_83->setText(QApplication::translate("MainWindow", "Std. Dur. Sonoro [ms]", nullptr));
        label_84->setText(QApplication::translate("MainWindow", "Rata de silencio [1/s]", nullptr));
        label_85->setText(QApplication::translate("MainWindow", "Dur. Prom. Silencio [ms]", nullptr));
        label_86->setText(QApplication::translate("MainWindow", "Std. Dur. Silencio [ms]", nullptr));
        label_87->setText(QApplication::translate("MainWindow", "Prom. F0 [Hz]", nullptr));
        label_88->setText(QApplication::translate("MainWindow", "Std. F0 [Hz]", nullptr));
        label_89->setText(QApplication::translate("MainWindow", "Max. F0 [Hz]", nullptr));
        label_90->setText(QApplication::translate("MainWindow", "Prom. Energia [dB]", nullptr));
        label_91->setText(QApplication::translate("MainWindow", "Std. Energia [dB]", nullptr));
        label_92->setText(QApplication::translate("MainWindow", "Max. Energia [dB]", nullptr));
        label_107->setText(QApplication::translate("MainWindow", "142->229", nullptr));
        label_108->setText(QApplication::translate("MainWindow", "22->39", nullptr));
        label_109->setText(QApplication::translate("MainWindow", "217->324", nullptr));
        label_110->setText(QApplication::translate("MainWindow", "7.0->9.4", nullptr));
        label_111->setText(QApplication::translate("MainWindow", "9.0->10.8", nullptr));
        label_112->setText(QApplication::translate("MainWindow", "16.9->18.8", nullptr));
        label_113->setText(QApplication::translate("MainWindow", "1.7->2.5", nullptr));
        label_114->setText(QApplication::translate("MainWindow", "292->521", nullptr));
        label_115->setText(QApplication::translate("MainWindow", "209->347", nullptr));
        label_116->setText(QApplication::translate("MainWindow", "0.3->0.6", nullptr));
        label_117->setText(QApplication::translate("MainWindow", "211->547", nullptr));
        label_118->setText(QApplication::translate("MainWindow", "6->271", nullptr));
        radarPros->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Prosodia", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "Mi casa tiene tres cuartos", nullptr));
        label_34->setText(QString());
        label_35->setText(QApplication::translate("MainWindow", "Oraci\303\263n leida", nullptr));
        label_36->setText(QApplication::translate("MainWindow", "Oraci\303\263n predicha", nullptr));
        label_37->setText(QApplication::translate("MainWindow", "WA", nullptr));
        label_38->setText(QString());
        label_39->setText(QApplication::translate("MainWindow", "DTW", nullptr));
        label_40->setText(QString());
        label_41->setText(QString());
        label_42->setText(QString());
        label_43->setText(QApplication::translate("MainWindow", "Omar, que vive cerca, trajo miel", nullptr));
        label_44->setText(QString());
        label_45->setText(QString());
        label_46->setText(QString());
        label_47->setText(QString());
        label_48->setText(QApplication::translate("MainWindow", "Laura sube al tren que pasa", nullptr));
        label_49->setText(QApplication::translate("MainWindow", "Los libros nuevos no caben en la mesa de la oficina", nullptr));
        label_50->setText(QString());
        label_51->setText(QString());
        label_52->setText(QString());
        label_53->setText(QString());
        label_54->setText(QString());
        label_55->setText(QApplication::translate("MainWindow", "Rosita Ni\303\261o, que pinta bien, don\303\263 sus cuadros ayer", nullptr));
        label_56->setText(QString());
        label_57->setText(QString());
        label_58->setText(QApplication::translate("MainWindow", "Luisa Rey compra el colch\303\263n duro que tanto le gusta", nullptr));
        label_59->setText(QString());
        label_60->setText(QString());
        label_61->setText(QString());
        label_62->setText(QApplication::translate("MainWindow", "Ayer fui al m\303\251dico. Qu\303\251 le pasa? Me pregunt\303\263.\n"
"Yo le dije: Ay doctor! Donde pongo el dedo me duele.\n"
"Tiene la u\303\261a rota?. S\303\255. Pues ya sabemos qu\303\251 es. \n"
"Deje su cheque a la salida.", nullptr));
        label_63->setText(QString());
        label_64->setText(QString());
        label_65->setText(QString());
        label_66->setText(QString());
        label_67->setText(QApplication::translate("MainWindow", "Promedio", nullptr));
        radarInt->setText(QString());
        label_137->setText(QApplication::translate("MainWindow", "Viste las noticias, yo v\303\255 ganar la medalla de plata en pesas, \n"
"ese muchacho tiene mucha fuerza", nullptr));
        label_138->setText(QString());
        label_139->setText(QString());
        label_146->setText(QString());
        label_147->setText(QString());
        label_148->setText(QApplication::translate("MainWindow", "Juan se rompi\303\263 una pierna cuando iba en la moto", nullptr));
        label_149->setText(QString());
        label_150->setText(QString());
        label_151->setText(QString());
        label_152->setText(QString());
        label_153->setText(QString());
        label_154->setText(QApplication::translate("MainWindow", "Estoy muy triste, ayer vi morir a un amigo", nullptr));
        label_155->setText(QString());
        label_156->setText(QApplication::translate("MainWindow", "Estoy muy preocupado, cada vez me es m\303\241s dificil hablar", nullptr));
        label_157->setText(QString());
        label_158->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "Inteligibilidad", nullptr));
        label_119->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_120->setText(QApplication::translate("MainWindow", "0 -> 4", nullptr));
        label_121->setText(QApplication::translate("MainWindow", "Capacidad respiratoria", nullptr));
        label_123->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_124->setText(QApplication::translate("MainWindow", "Movimiento de labios", nullptr));
        label_125->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_126->setText(QApplication::translate("MainWindow", "Movimiento de paladar", nullptr));
        label_128->setText(QApplication::translate("MainWindow", "Movimiento de Laringe", nullptr));
        label_130->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_131->setText(QApplication::translate("MainWindow", "Rapidez de la lengua", nullptr));
        label_133->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_134->setText(QApplication::translate("MainWindow", "Inteligibilidad", nullptr));
        label_135->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_122->setText(QApplication::translate("MainWindow", "0 -> 4", nullptr));
        label_127->setText(QApplication::translate("MainWindow", "0 -> 4", nullptr));
        label_129->setText(QApplication::translate("MainWindow", "0 -> 4", nullptr));
        label_132->setText(QApplication::translate("MainWindow", "0 -> 4", nullptr));
        label_136->setText(QApplication::translate("MainWindow", "0 -> 4", nullptr));
        label_140->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_141->setText(QApplication::translate("MainWindow", "0 -> 52", nullptr));
        label_142->setText(QApplication::translate("MainWindow", "Escala total de disartria (mFDA)", nullptr));
        evalmFDA->setText(QString());
        label_143->setText(QApplication::translate("MainWindow", "0->128", nullptr));
        label_144->setText(QApplication::translate("MainWindow", "Total MDS-UPDRS-III ", nullptr));
        label_145->setText(QApplication::translate("MainWindow", "0", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QApplication::translate("MainWindow", "Evaluaci\303\263n", nullptr));
        label_68->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOWSPANISH_H
