#ifndef STRINGS_H
#define STRINGS_H

#endif

#define spanish

#ifdef english

#define button1    "../PDTool/button1.png"
#define button2    "../PDTool/button2.png"
#define button3    "../PDTool/button3.png"
#define button4    "../PDTool/button4.png"
#define button5    "../PDTool/button5.png"
#define button5stop "../PDTool/button5stop.png"
#define logo       "../PDTool/Logo.png"
#define button5rec "../PDTool/button5rec.png"
#define button6play "../PDTool/button6play.png"
#define listTasks  "/A/"<<"/E/"<<"/I/"<<"/O/"<<"/U/"<<"Modulated Vowels"<<"Pa-Ta-Ka"<<"Pa-Ka-Ta"<<"Pe-Ta-Ka"<<"Pa"<<"Ta"<<"Ka"<<"Words"<<"sentence 1"<<"sentence 2"<<"sentence 3"<<"sentence 4"<<"sentence 5"<<"sentence 6"<<"sentence 7"<<"sentence 8"<<"sentence 9"<<"sentence 10"<<"Read Text"<<"Monologue"
#define xaxistime  "Time (sec)"
#define yaxisA     "Amplitude"
#define yaxisfreq  "Frequency (Hz)"
#define xaxisF1    "Formant 1(Hz)"
#define yaxisF2    "Formant 2(Hz)"
#define xaxisBBE   "Number of the Bark band"
#define yaxislogE  "Energy (dB)"
#define chooseA    "Choose file of vowel /A/"
#define chooseE    "Choose file of vowel /E/"
#define chooseI    "Choose file of vowel /I/"
#define chooseO    "Choose file of vowel /O/"
#define chooseU    "Choose file of vowel /U/"
#define choosecont "Choose file of continuous speech"
#define chooses1   "Choose file of sentence 1 (Mi Casa)"
#define chooses2   "Choose file of sentence 2 (Omar)"
#define chooses3   "Choose file of sentence 3 (Laura)"
#define chooses4   "Choose file of sentence 4 (Los libros)"
#define chooses5   "Choose file of sentence 5 (Rosita)"
#define chooses6   "Choose file of sentence 6 (Luisa)"
#define chooses7   "Choose file of sentence 7 (Viste las noticias)"
#define chooses8   "Choose file of sentence 8 (Juan)"
#define chooses9   "Choose file of sentence 9 (Estoy muy triste)"
#define chooses10  "Choose file of sentence 10 (Estoy muy preocupado)"
#define choosesRT  "Choose file of the read text"
#define report     "/../reporteNeuroSpeech.htm"
#define Onset      "Onset"
#define Offset     "Offset"
#define repeat     "Please repeat this recording"
#define phonation  "Phonation"
#define articulation  "Articulation"
#define prosody    "Prosody"
#define intelligibility  "Intelligibility"
#define evaluation  "Evaluation"
#define nameP       "First Name"
#define Lastname    "Last Name"
#define playExample "Play Example"
#define createReport "Create Report"
#define energyLab   "Energy (dB)"
#define vRateLab    "Voiced Rate (1/s)"
#define avgVoicedLab "Avg. Dur. Voiced (ms)"
#define stdVoicedLab "Std. Dur. Voiced (ms)"
#define silRateLab  "Silence Rate (1/s)"
#define avgSilLab   "Avg. Dur. Silence (ms)"
#define stdSilLab   "Std. Dur. Silence (ms)"
#define avgF0Lab    "Avg. F0 (Hz)"
#define stdF0Lab    "Std. F0 (Hz)"
#define maxF0Lab    "Max. F0 (Hz)"
#define avgEnLab    "Avg. Energy (dB)"
#define stdEnLab    "Std. Energy (dB)"
#define maxEnLab    "Max. Energy (dB)"
#define readsent    "Read sentence"
#define predsent    "Predicted sentence"
#define respCap     "Respiration Capability"
#define LipsMov     "Lips Movement"
#define PalMov      "Palate Movement"
#define LarMov      "Larinx Movement"
#define TongueVel   "Tongue Velocity"
#define mfdasc      "Total Dysarthria Score"
#define updrssc     "Total UPDRS-III score"
#define phonScript  "phonVowels.py "
#define artVowelsScript "artVowels.py "
#define artContScript "artCont.py "
#define intScript   "intelligibility.py "
#define prosScript "prosody.py "
#define mfdaScript "predictmFDA.py "


#endif // english

#ifdef spanish

#define button1    "../PDTool/button1Spanish.png"
#define button2    "../PDTool/button2Spanish.png"
#define button3    "../PDTool/button3Spanish.png"
#define button4    "../PDTool/button4Spanish.png"
#define button5    "../PDTool/button5Spanish.png"
#define button5stop "../PDTool/button5stop.png"
#define logo       "../PDTool/Logo.png"
#define button5rec "../PDTool/button5rec.png"
#define button6play "../PDTool/button6play.png"
#define listTasks  "/A/"<<"/E/"<<"/I/"<<"/O/"<<"/U/"<<"Vocales Moduladas"<<"Pa-Ta-Ka"<<"Pa-Ka-Ta"<<"Pe-Ta-Ka"<<"Pa"<<"Ta"<<"Ka"<<"Palabras"<<"frase 1"<<"frase 2"<<"frase 3"<<"frase 4"<<"frase 5"<<"frase 6"<<"frase 7"<<"frase 8"<<"frase 9"<<"frase 10"<<"Texto leido"<<"Monologo"
#define xaxistime  "Tiempo (s)"
#define yaxisA     "Amplitud"
#define yaxisfreq  "Frecuencia (Hz)"
#define xaxisF1    "Formante 1(Hz)"
#define yaxisF2    "Formante 2(Hz)"
#define xaxisBBE   "Número de banda de Bark"
#define yaxislogE  "Energia (dB)"
#define chooseA    "Seleccione un archivo de la vocal /A/"
#define chooseE    "Seleccione un archivo de la vocal /E/"
#define chooseI    "Seleccione un archivo de la vocal /I/"
#define chooseO    "Seleccione un archivo de la vocal /O/"
#define chooseU    "Seleccione un archivo de la vocal /U/"
#define choosecont "Seleccione un archivo de habla continua"
#define chooses1   "Seleccione un archivo de la frase 1 (Mi Casa)"
#define chooses2   "Seleccione un archivo de la frase 2 (Omar)"
#define chooses3   "Seleccione un archivo de la frase 3 (Laura)"
#define chooses4   "Seleccione un archivo de la frase 4 (Los libros)"
#define chooses5   "Seleccione un archivo de la frase 5 (Rosita)"
#define chooses6   "Seleccione un archivo de la frase 6 (Luisa)"
#define chooses7   "Seleccione un archivo de la frase 7 (Viste las noticias)"
#define chooses8   "Seleccione un archivo de la frase 8 (Juan)"
#define chooses9   "Seleccione un archivo de la frase 9 (Estoy muy triste)"
#define chooses10  "Seleccione un archivo de la frase 10 (Estoy muy preocupado)"
#define choosesRT  "Seleccione un archivo del texto leido"
#define report     "/../reporteNeuroSpeechSpanish.htm"
#define Onset      "Onset"
#define Offset     "Offset"
#define repeat     "Por favor repita esta grabación"
#define phonation  "Fonación"
#define articulation  "Articulación"
#define prosody    "Prosodia"
#define intelligibility  "Inteligibilidad"
#define evaluation  "Evaluación"
#define nameP       "Nombre"
#define Lastname    "Apellidos"
#define playExample "Reproducir Ejemplo"
#define createReport "Crear Reporte"
#define energyLab   "Energia (dB)"
#define vRateLab    "Rata Sonoros (1/s)"
#define avgVoicedLab "Dur.Prom.Sonoros (ms)"
#define stdVoicedLab "Dur.Std.Sonoros (ms)"
#define silRateLab  "Rata Silencio (1/s)"
#define avgSilLab   "Dur.Prom.Silencio (ms)"
#define stdSilLab   "Dur.Std.Silencio (ms)"
#define avgF0Lab    "Prom. F0 (Hz)"
#define stdF0Lab    "Std. F0 (Hz)"
#define maxF0Lab    "Max. F0 (Hz)"
#define avgEnLab    "Prom. Energia (dB)"
#define stdEnLab    "Std. Energia (dB)"
#define maxEnLab    "Max. Energia (dB)"
#define readsent    "Frase leida"
#define predsent    "Frase predicha"
#define respCap     "Capacidad Respiratoria"
#define LipsMov     "Movimiento de Labios"
#define PalMov      "Movimiento de Paladar"
#define LarMov      "Movimiento de Laringe"
#define TongueVel   "Velocidad de la lengua"
#define mfdasc      "Nivel total de disartria"
#define updrssc     "Nivel total de UPDRS-III"
#define phonScript  "phonVowelsSpanish.py "
#define artVowelsScript "artVowelsSpanish.py "
#define artContScript "artCont.py "
#define intScript   "intelligibility.py "
#define prosScript "prosodySpanish.py "
#define mfdaScript "predictmFDASpanish.py "

#endif
